### ISSUE TITLE
Cannot load media resource annotation ontology

### ISSUE THREAD

**Issue by jerdeb** [VisualDataWeb/WebVOWL#97] opened 2017-07-07 11:21 UTC
Hi Vitalis/Steffen,

I am trying to visualise an ontology (http://www.w3.org/ns/ma-ont#) on WebVOWL, however, it seems that the ontology is not being dereferenced by the application. This is the error that I am getting:
`There is no OWL input under the given IRI(http://www.w3.org/ns/ma-ont). Please try to load the OWL file directly.`

I think the problem is not entirely WebVOWLs fault, as the namespace (strangely enough) gives a 200 OK for the ontology's turtle file. Nevertheless, asking for the rdf+xml of the namespace (`curl -H "Accept: application/rdf+xml" http://www.w3.org/ns/ma-ont#`), the RDF serialised file is returned. Therefore, I think that your application should _by default_ ask for the RDF file, if turtle is not supported.

Cheers,
Jer

**Comment by vitalis-wiens** [comment] 2017-07-07 12:28
Hi Jeremy,
I will look into it, meanwhile you can use the owl2vowl tool in order to transform the ontology into a json format for webvowl (i`ve tested it and it works with this workaround), then you can load the json file in webvowl.

Cheers, Vitalis

**Comment by jerdeb** [comment] 2017-07-07 14:54
Thanks! Yes I actually downloaded the RDF serialised file and used it instead :). Maybe you should add the owl2vowl in the pipeline as a temporary workaround then. I will leave this issue open as a reminder for you to solve this mentioned issue ;)

**Comment by jerdeb** [comment] 2017-07-13 14:34
Hi @vitalis-wiens,

Apparently this problem is not just related to the media ontology, but to most ontologies in LOV. For example: http://lov.okfn.org/dataset/lov/vocabs/frappe . In LOV there is the function to display the vocab in WebVOWL, but since WebVOWL is not managing to dereference ontologies, it is not working.

**Comment by jo-tud** [comment] 2017-10-12 14:02
Same problem for this ontology: http://visualdataweb.de/webvowl/#iri=http://ethon.consensys.net/EthOn.ttl
I'd like to link to the visualisation but it's not possible (https://github.com/ConsenSys/EthOn/blob/master/README.md)

**Comment by christopheralcock** [comment] 2017-10-12 14:31
at work we use webvowl a lot, it's a fantastic tool, but we were running into the issues that people in this thread are having, so we've deployed our own instance of webvowl 1.0.4 to our own server, where it works every time (and where we can make minor tweaks to the code, such as turning off automatic setting of "degree of collapsing" to 0) .
i've tried the ontologies from this thread on our instance and they all load fine, if slowly.
i'd recommend this approach to anyone having problems who has the ability to set up a Tomcat server:
http://vowl.visualdataweb.org/webvowl.html

**Comment by steffen-l** [comment] 2017-10-12 19:41
We will look into it but these sound like different issues. We are aware the current version of the OWL2VOWL converter is not working for all ontologies, but will check the server configuration and pipelining of the public WebVOWL instance for a quick fix in this case.

@christopheralcock: Did you install the WAR bundle we provide at http://vowl.visualdataweb.org/webvowl.html ? Can you really open BOTH ontologies (EthOn and FraPPE) on your WebVOWL instance? Regarding your second comment: Any suggestion of how to change the "automatic collapsing" but avoiding overly large ontology graphs creating information overload and risking the browser to freeze? We are always happy about pointers, hints, and suggestions...

**Comment by christopheralcock** [comment] 2017-10-13 09:29
@steffen-l 
yep we used your WAR, it was incredibly useful.
have retried the ontologies and my apologies - EthOn and http://www.w3.org/ns/ma-ont# works but FraPPE doesn't, and I imagine the issue is as @jerdeb has described, sorry to confuse things.

As for the automatic collapsing, I see how it's a useful feature and necessary to have by default, but basically I'd send a webvowl link to developers working with our database and they'd come back saying they couldn't find this or that class as it had been filtered.
Ideally I'd like to be able to pass a param in the url like visualdataweb.de/webvowl/#iri=https://example.com/ontology.owl&collapse=false or something so I could share that link and take the blame if it freezes their browser

**Comment by steffen-l** [comment] 2017-10-13 10:01
Thanks for your feedback, @christopheralcock. The URL-based configuration is already on our issue list. Adding a Boolean value for the automatic collapsing (and other default features) is a good idea.

Regarding the ontologies:
-  http://www.w3.org/ns/ma-ont# can be loaded with the public WebVOWL instance: http://visualdataweb.de/webvowl/#iri=http://www.w3.org/ns/ma-ont#

- http://ethon.consensys.net/EthOn.ttl can currently only be loaded when being saved as a file and uploaded to the public WebVOWL instance (might be content negotiation, as stated by @jerdeb - we are checking that)

- http://lov.okfn.org/dataset/lov/vocabs/frappe seems to cause trouble due to the imported ontologies (there seems to be an issue with the prov ontology). We'll check that too.

**Comment by steffen-l** [comment] 2017-11-29 14:28
@jerdeb and @jo-tud: looks like this issue has been resolved as both your ontologies can now be loaded by the public WebVOWL instance (i.e.: http://www.w3.org/ns/ma-ont# and http://ethon.consensys.net/EthOn.ttl). The third one (http://lov.okfn.org/dataset/lov/vocabs/frappe) still causes an error though (see my comment above).

@christopheralcock: URL parameters have been added to the latest version - see [WebVOWL 1.0.6](http://vowl.visualdataweb.org/webvowl.html#releases) and try the new "Export as URL" feature.

**Comment by vitalis-wiens** [comment] 2018-09-07 13:08
Missing imports are now possible with the new loading indicator
(results in a warning for the user, however the main ontology and found imports will be loaded )

Additional information is provided now while loading the ontology. 

w.r.t the ethon ontology, the server configuration results in the error code 403 
also protégée is not able to load it form the url.

the same issue seems to be with the frappe ontology. 

Closing this issue :)

**Closed by vitalis-wiens** 2018-09-07 13:08 UTC
